export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const CLEAR = 'CLEAR'

export const SET_FILTER_REQUEST = 'SET_FILTER_REQUEST'
export const SET_FILTER_SUCCESS = 'SET_FILTER_SUCCESS'
export const SET_FILTER_ERROR = 'SET_FILTER_ERROR'
export const CLEAR_FILTER = 'CLEAR_FILTER'
